server:
  port: 8083

spring:
  application:
    name: Admin Application
  datasource:
    url: jdbc:postgresql://localhost:5432/heuy_db
    username: ridwan
    password: psql
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true

